Desugar lambda function and method reference.
Why:

We use dx to convert classes to dex.(Becasue d8 is too hard to build)

Android don't support invoke-dynamic until API 26+,
In d8, lambda function is desugared to annoymous class by classes bytecode translation before converted to dex (if min-sdk <= 26).
and even with min-sdk 33, d8 will desugar it instead of invoke-dynamic due to no LambdaMetadataFactory in Android runtime.(see https://slack-chats.kotlinlang.org/t/8990438/as-a-android-developer-that-only-writes-kotlin-code-what-jvm#30c52ac9-070d-4bfe-baa1-85b3e3487a06 and https://jakewharton.com/androids-java-8-support/)

However dx doesn't have this desugar ability.

dx could translate lambda function to invoke-custom with
--min-sdk-version=26, and the result bytecode:
```invoke-custom {v1}, call_site_7("onTerminated",(Lcom/genymobile/scrcpy/Server$Completion;)Lcom/genymobile/scrcpy/AsyncProcessor$TerminationListener;,(Z)V,invoke-static@Lcom/genymobile/scrcpy/Server;->lambda$scrcpy$0(Lcom/genymobile/scrcpy/Server$Completion;Z)V,(Z)V)@Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;```
, but the required LambdaMetadataFactory isn't implemented in Android side.

So error
```
[server] ERROR: Exception from call site #25 bootstrap method
java.lang.BootstrapMethodError: Exception from call site #25 bootstrap method
    at com.genymobile.scrcpy.Server.internalMain(Server. java:229)
    at com.genymobile.scrcpy.Server.main(Server.java:215)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit. java: 367)
Caused by: java.lang.ClassCastException: Bootstrap method returned null
    ... 4 more
```
will be returned.

Ref:
https://cs.android.com/android/platform/superproject/+/android-latest-release:libcore/ojluni/src/main/java/java/lang/invoke/LambdaMetafactory.java;l=330?q=lambdametafactory

What we do:

Manually desugar lambda functions and method references to annoymous classes.

How to find which to modify:
1. dx will complain about this if you don't specific
   --min-sdk-version=26
2. grep " -> " and "::"