Force InvokeVirtual instead of InvokeInterface
Why

To compile scrcpy server which could run on old devices with recent JDK.

error log
```
java.lang.IncompatibleClassChangeError: The method 'java.lang.Class java.lang.Object.getClass()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'com.genymobile.scrcpy.wrappers.PowerManager' appears in

        at com.genymobile.scrcpy.wrappers.PowerManager.getIsScreenOnMethod(PowerManager.java:34)
        at com.genymobile.scrcpy.wrappers.PowerManager.isScreenOn(PowerManager.java:43)
        at com.genymobile.scrcpy.device.Device.isScreenOn(Device.java:88)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:234)
        at com.genymobile.scrcpy.control.Controller.access$500(Controller.java:45)
        at com.genymobile.scrcpy.control.Controller$3.run(Controller.java:289)
        at java.lang.Thread.run(Thread.java:818)
```

IInterface
in JDK <= 17 , it will be
```
      48: getfield      #22                 // Field manager:Landroid/os/IInterface;
      51: invokeinterface #58,  1           // InterfaceMethod android/os/IInterface.getClass:()Ljava/lang/Class;
      56: ldc           #59                 // String isInteractive
```

In JDK >= 17 , it will be
```
      48: getfield      #22                 // Field manager:Landroid/os/IInterface;
      51: invokeinterface #58,  1           // InterfaceMethod android/os/IInterface.getClass:()Ljava/lang/Class;
      56: ldc           #59                 // String isInteractive
```

D8 has a fix for this change (by changing from invokeinterface to
invokevirtual), but we use dx it will convert to dex without
modification.

Ref:
JDK's change:
https://bugs.openjdk.org/browse/JDK-8272564
D8 fix
https://issuetracker.google.com/issues/218298666
Related
Links to previous two urls
https://github.com/android/android-test/issues/1642
Said JDK<=17 is OK
https://github.com/bytedance/Fastbot_Android/issues/290

What

Cast all IInterface instances to object before calling `getClass`

// Instead of:
IInterface myInterface = ...;
Class<?> clazz = myInterface.getClass();

// Do this:
Class<?> clazz = ((Object) myInterface).getClass();

How

search IInterface, and getClass(), mostly in wrappers subfolder